apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inkblot-web-staging
resources:
  - namespace.yaml
  - ../../base
patches:
  - target:
      kind: Ingress
      name: web-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging-web.inkblot.studio
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging-web.inkblot.studio
      - op: replace
        path: /spec/tls/0/secretName
        value: staging-web-tls
