apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inkblot-web-prod
resources:
  - namespace.yaml
  - ../../base
patches:
  - target:
      kind: Deployment
      name: web-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: HorizontalPodAutoscaler
      name: web-app
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 8
  - target:
      kind: Ingress
      name: web-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: web.inkblot.studio
      - op: replace
        path: /spec/tls/0/hosts/0
        value: web.inkblot.studio
      - op: replace
        path: /spec/tls/0/secretName
        value: web-prod-tls
